#![feature(test)]

extern crate test;
extern crate comrak;

use test::Bencher;
use comrak::ComrakOptions;

use comrak::markdown_to_html;
use comrak::html_to_commonmark;

static STR: &'static str = concat!( "My **document**.\n",
    "\n",
    "It's mine.\n",
    "\n",
    "> Yes.\n",
    "\n",
    "## Hi!\n",
    "\n",
    "Okay.\n",
    "``` rust yum\n", "fn main<'a>();\n", "```\n",
    "2. Hello.\n", "3. Hi.\n",
    "- Hello.\n", "- Hi.\n",
    "---\n", "\n", "- - -\n", "\n", "\n", "_        _   _\n",
    "Hi\n", "==\n", "\n", "Ok\n", "-----\n",
    "<script\n",
    "*ok* </script> *ok*\n",
    "\n",
    "*ok*\n",
    "\n",
    "*ok*\n",
    "\n",
    "<pre x>\n",
    "*ok*\n",
    "</style>\n",
    "*ok*\n",
    "<style>\n",
    "*ok*\n",
    "</style>\n",
    "\n",
    "*ok*\n",
    "   <!-- abc\n", "\n", "ok --> *hi*\n", "*hi*\n",
    " <? o\n", "k ?> *a*\n", "*a*\n",
    "<!X >\n", "ok\n", "<!X\n", "um > h\n", "ok\n",
    "<![CDATA[\n",
    "\n",
    "hm >\n",
    "*ok*\n",
    "]]> *ok*\n",
    "*ok*\n",
    " </table>\n", "*x*\n", "\n", "ok\n", "\n", "<li\n", "*x*\n",
    "<a b >\n",
    "ok\n",
    "\n",
    "<a b=>\n",
    "ok\n",
    "\n",
    "<a b \n",
    "<a b> c\n",
    "ok\n",
    "<a b c=x d='y' z=\"f\" >\n", "ok\n", "\n", "ok\n",
    "Some `code\\` yep.\n",
    "Some \\`fake code\\`.\n",
    "\n",
    "Some fake linebreaks:\\\n",
    "Yes.\\\n",
    "See?\n",
    "\n",
    "Ga\\rbage.\n",
    "This is &amp;, &copy;, &trade;, \\&trade;, &xyz;, &NotEqualTilde;.\n",
    "\n",
    "&#8734; &#x221e;\n",
    "URI autolink: <https://www.pixiv.net>\n",
    "\n",
    "Email autolink: <bill@microsoft.com>\n",
    "\n",
    "* Inline <em>tag</em> **ha**.\n",
    "* Inline <!-- comment --> **ha**.\n",
    "* Inline <? processing instruction ?> **ha**.\n",
    "* Inline <!DECLARATION OKAY> **ha**.\n",
    "* Inline <![CDATA[ok]ha **ha** ]]> **ha**.\n",
    "Where are you [going](https://microsoft.com (today))?\n",
    "\n",
    "[Where am I?](/here)\n",
    "I am ![eating [things](/url)](http://i.imgur.com/QqK1vq7.png).\n",
    "This [is] [legit], [very][honestly] legit.\n",
    "\n",
    "[legit]: ok\n",
    "[honestly]: sure \"hm\"\n",
    "This is ~strikethrough~.\n",
    "\n",
    "As is ~~this, okay~~?\n",
    "| a | b |\n", "|---|:-:|\n", "| c | d |\n",
    "www.autolink.com\n",
    "john@smith.com\n",
    "https://google.com/search\n",
    "hi <xmp> ok\n", "\n", "<xmp>\n",
    "* [ ] Red\n",
    "* [x] Green\n",
    "* [ ] Blue\n",
    "<!-- end list -->\n",
    "1. [ ] Bird\n",
    "2. [ ] McHale\n",
    "3. [x] Parish\n",
    "<!-- end list -->\n",
    "* [ ] Red\n",
    "  * [x] Green\n",
    "    * [ ] Blue\n",
    "e = mc^2^.\n");

static STR_2: &'static str = concat!(
    "<p>My <strong>document</strong>.</p>\n",
    "<p>It's mine.</p>\n",
    "<blockquote>\n",
    "<p>Yes.</p>\n",
    "</blockquote>\n",
    "<h2>Hi!</h2>\n",
    "<p>Okay.</p>\n",
    "<pre><code class=\"language-rust\">fn main&lt;'a&gt;();\n",
    "</code></pre>\n","<ol start=\"2\">\n",
    "<li>Hello.</li>\n",
    "<li>Hi.</li>\n",
    "</ol>\n","<ul>\n", "<li>Hello.</li>\n", "<li>Hi.</li>\n", "</ul>\n",
    "<hr />\n", "<hr />\n", "<hr />\n","<h1>Hi</h1>\n", "<h2>Ok</h2>\n",
    "<script>\n",
    "*ok* </script> *ok*\n",
    "<p><em>ok</em></p>\n",
    "<p><em>ok</em></p>\n",
    "<pre x>\n",
    "*ok*\n",
    "</style>\n",
    "<p><em>ok</em></p>\n",
    "<style>\n",
    "*ok*\n",
    "</style>\n",
    "<p><em>ok</em></p>\n",
    "   <!-- abc\n",
    "\n",
    "ok --> *hi*\n",
    "<p><em>hi</em></p>\n"," <? o\n", "k ?> *a*\n", "<p><em>a</em></p>\n",
    "<!X >\n", "<p>ok</p>\n", "<!X\n", "um > h\n", "<p>ok</p>\n","<![CDATA[\n",
    "\n",
    "hm >\n",
    "*ok*\n",
    "]]> *ok*\n",
    "<p><em>ok</em></p>\n"," </table>\n", "*x*\n", "<p>ok</p>\n", "<li\n", "*x*\n",
    "<a b >\n",
    "ok\n",
    "<p>&lt;a b=&gt;\n",
    "ok</p>\n",
    "<p>&lt;a b\n",
    "<a b> c\n",
    "ok</p>\n","<a b c=x d='y' z=\"f\" >\n", "ok\n", "<p>ok</p>\n",
    "Some `code\\` yep.\n",
    "<p>Some <code>code\\</code> yep.</p>\n",
    "<p>Some `fake code`.</p>\n",
    "<p>Some fake linebreaks:<br />\n",
    "Yes.<br />\n",
    "See?</p>\n",
    "<p>Ga\\rbage.</p>\n",
    "<p>This is &amp;, ©, ™, &amp;trade;, &amp;xyz;, \u{2242}\u{338}.</p>\n",
    "<p>∞ ∞</p>\n",
    "<p>URI autolink: <a \
          href=\"https://www.pixiv.net\">https://www.pixiv.net</a></p>\n",
    "<p>Email autolink: <a \
          href=\"mailto:bill@microsoft.com\">bill@microsoft.com</a></p>\n",
    "<ul>\n",
    "<li>Inline <em>tag</em> <strong>ha</strong>.</li>\n",
    "<li>Inline <!-- comment --> <strong>ha</strong>.</li>\n",
    "<li>Inline <? processing instruction ?> <strong>ha</strong>.</li>\n",
    "<li>Inline <!DECLARATION OKAY> <strong>ha</strong>.</li>\n",
    "<li>Inline <![CDATA[ok]ha **ha** ]]> <strong>ha</strong>.</li>\n",
    "</ul>\n",
    "<p>Where are you <a href=\"https://microsoft.com\" \
          title=\"today\">going</a>?</p>\n",
    "<p><a href=\"/here\">Where am I?</a></p>\n",
    "<p>I am <img src=\"http://i.imgur.com/QqK1vq7.png\" alt=\"eating things\" \
          />.</p>\n",
    "<p>This [is] <a href=\"ok\">legit</a>, <a href=\"sure\" title=\"hm\">very</a> \
          legit.</p>\n",
    "<p>This is <del>strikethrough</del>.</p>\n",
    "<p>As is <del>this, okay</del>?</p>\n",
    "<table>\n",
    "<thead>\n",
    "<tr>\n",
    "<th>a</th>\n",
    "<th align=\"center\">b</th>\n",
    "</tr>\n",
    "</thead>\n",
    "<tbody>\n",
    "<tr>\n",
    "<td>c</td>\n",
    "<td align=\"center\">d</td>\n",
    "</tr></tbody></table>\n","<p><a href=\"http://www.autolink.com\">www.autolink.com</a></p>\n",
      "<p><a href=\"mailto:john@smith.com\">john@smith.com</a></p>\n",
      "<p><a href=\"https://google.com/search\">https://google.\
               com/search</a></p>\n","<p>hi &lt;xmp> ok</p>\n", "&lt;xmp>\n",
    "<ul>\n",
    "<li><input type=\"checkbox\" disabled=\"\" /> Red</li>\n",
    "<li><input type=\"checkbox\" disabled=\"\" checked=\"\" /> Green</li>\n",
    "<li><input type=\"checkbox\" disabled=\"\" /> Blue</li>\n",
    "</ul>\n",
    "<!-- end list -->\n",
    "<ol>\n",
    "<li><input type=\"checkbox\" disabled=\"\" /> Bird</li>\n",
    "<li><input type=\"checkbox\" disabled=\"\" /> McHale</li>\n",
    "<li><input type=\"checkbox\" disabled=\"\" checked=\"\" /> Parish</li>\n",
    "</ol>\n",
    "<!-- end list -->\n",
    "<ul>\n",
    "<li><input type=\"checkbox\" disabled=\"\" /> Red\n",
    "<ul>\n",
    "<li><input type=\"checkbox\" disabled=\"\" checked=\"\" /> Green\n",
    "<ul>\n",
    "<li><input type=\"checkbox\" disabled=\"\" /> Blue</li>\n",
    "</ul>\n",
    "</li>\n",
    "</ul>\n",
    "</li>\n",
    "</ul>\n","<p>e = mc<sup>2</sup>.</p>\n");

#[bench]
fn bench_html_formatting(b: &mut Bencher) {
    let mut options = ComrakOptions::default();

    b.iter(|| for _ in 0..1000 {
        markdown_to_html(&STR.chars().collect::<String>(), &options);
    })
}

#[bench]
fn bench_commonmark_formatting(b: &mut Bencher) {
    let mut options = ComrakOptions::default();

    b.iter(|| for _ in 0..1000 {
        html_to_commonmark(&STR.chars().collect::<String>(), &options);
    })
}
